name: dutch_receipt_scanner
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.11.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  file_picker: ^8.1.7
  cross_file: ^0.3.3+7
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_commons: ^0.9.0
  path: ^1.8.3
  image: ^4.5.2
  intl: ^0.20.2
  uuid: ^4.2.2
  firebase_ml_model_downloader: ^0.3.2+1
  firebase_core: ^3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true